#CREATE DATABASE programming_project;

USE programming_project;

CREATE TABLE flight_data  
( 
FL_DATE VARCHAR(50),
MKT_CARRIER VARCHAR(50),
MKT_CARRIER_FL_NUM INT,
ORIGIN VARCHAR(50),
ORIGIN_CITY_NAME VARCHAR(50),
ORIGIN_STATE_ABR VARCHAR(50),
ORIGIN_WAC INT,
DEST VARCHAR(50),
DEST_CITY_NAME VARCHAR(50),
DEST_STATE_ABR VARCHAR(50),
DEST_WAC INT,
CRS_DEP_TIME INT,
DEP_TIME INT,
CRS_ARR_TIME INT,
ARR_TIME INT,
CANCELLED INT,
DIVERTED INT,
DISTANCE INT
);

SELECT * FROM flight_data;